// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBicks.EntityFramework;

namespace MiniBicks.DataContext.Migrations
{
    [DbContext(typeof(MiniBicksContext))]
    [Migration("20191120181523_FraisModel")]
    partial class FraisModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview3.19554.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniBicks.Entities.Adresse", b =>
                {
                    b.Property<Guid>("ID_Adresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CodePostal")
                        .HasColumnType("int");

                    b.Property<int>("NumeroRue")
                        .HasColumnType("int");

                    b.Property<int>("PaysEnum")
                        .HasColumnType("int");

                    b.Property<string>("Rue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Adresse");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("MiniBicks.Entities.Conge", b =>
                {
                    b.Property<Guid>("ID_Conge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CongeValiditeEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID_DureeConge")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeCongeEnum")
                        .HasColumnType("int");

                    b.HasKey("ID_Conge");

                    b.HasIndex("ID_DureeConge");

                    b.HasIndex("ID_User");

                    b.ToTable("Conges");
                });

            modelBuilder.Entity("MiniBicks.Entities.DureeConge", b =>
                {
                    b.Property<Guid>("ID_DureeConge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int>("PaysEnum")
                        .HasColumnType("int");

                    b.Property<int>("TypeCongeEnum")
                        .HasColumnType("int");

                    b.HasKey("ID_DureeConge");

                    b.ToTable("DureeConges");
                });

            modelBuilder.Entity("MiniBicks.Entities.Frai", b =>
                {
                    b.Property<Guid>("ID_Frai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FraiEnum")
                        .HasColumnType("int");

                    b.Property<Guid>("ID_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MontantTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Frai");

                    b.HasIndex("ID_User");

                    b.ToTable("Frais");
                });

            modelBuilder.Entity("MiniBicks.Entities.User", b =>
                {
                    b.Property<Guid>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID_Adresse")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ID_Responsable")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleEnum")
                        .HasColumnType("int");

                    b.HasKey("ID_User");

                    b.HasIndex("ID_Adresse");

                    b.HasIndex("ID_Responsable");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MiniBicks.Entities.Conge", b =>
                {
                    b.HasOne("MiniBicks.Entities.DureeConge", "DureeConge")
                        .WithMany()
                        .HasForeignKey("ID_DureeConge")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniBicks.Entities.User", "User")
                        .WithMany("ListeConge")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniBicks.Entities.Frai", b =>
                {
                    b.HasOne("MiniBicks.Entities.User", "User")
                        .WithMany("ListeFrais")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniBicks.Entities.User", b =>
                {
                    b.HasOne("MiniBicks.Entities.Adresse", "Adresse")
                        .WithMany()
                        .HasForeignKey("ID_Adresse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniBicks.Entities.User", "Responsable")
                        .WithMany()
                        .HasForeignKey("ID_Responsable");
                });
#pragma warning restore 612, 618
        }
    }
}
